/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

class UnknownException extends AppException {
  UnknownException([String? code, String? message])
      : super(
          code ?? 'unknown',
          message ?? 'Something went wrong! Please try again.',
        );
}
