name: Flutter Birds Main Workflow

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  semantic-pull-request:
    uses: ./.github/workflows/semantic_pull_request.yaml

  analyze:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      flutter_channel: stable
